package org.usfirst.frc2974.SoccerBot.commands;

import org.usfirst.frc2974.SoccerBot.Robot;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2974.SoccerBot.subsystems.*;
/**
 *
 */
public class IntakeBackground extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS

 
    public IntakeBackground() {
        super();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.intake);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    private enum CurrentState{
    		Initialize,
    		Hold,
    };
    //private ArmPosition armPosition;
    private CurrentState currentState;
    private double SecondsToElapse = 4;
    // Called just before this Command runs the first time
    protected void initialize() {
    	currentState = CurrentState.Initialize;
    	//armPosition = new ArmPosition;
    	setTimeout(SecondsToElapse);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	switch(currentState){
    	case Initialize:
    		Robot.intake.setArmMovement(Intake.ArmMovement.up);
    		if (isTimedOut()){
    			currentState = CurrentState.Hold;
    		}
    		break;
    	case Hold:
    		Robot.intake.setArmMovement(Intake.ArmMovement.up);
    		break;
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
