package org.usfirst.frc2974.SoccerBot.commands;

import org.usfirst.frc2974.SoccerBot.Robot;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2974.SoccerBot.subsystems.*;
/**
 *
 */
public class IntakeBackground extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS

 
    public IntakeBackground() {
        super();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.intake);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    
    //private ArmPosition armPosition;
    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.intake.setMotorPower(0); 	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Intake.ArmMovement currentAction = Robot.intake.getAction();
    	switch (Robot.intake.getArmPosition()){
    	case up:
    	case high:
    		if(currentAction != Intake.ArmMovement.fall){
    			Robot.intake.setArmMovement(Intake.ArmMovement.fall);
    		}
    		break;
    	case dribble:
    		if(currentAction != Intake.ArmMovement.block){
    			Robot.intake.setArmMovement(Intake.ArmMovement.block);
    		}
    		break;
    	case low:
    	case flat:
    		if(currentAction != Intake.ArmMovement.up){
    			Robot.intake.setArmMovement(Intake.ArmMovement.up);
    		}
    		break;
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
