// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.team2974.robot.subsystems;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import frc.team2974.robot.RobotMap;
import frc.team2974.robot.commands.Drive;


/**
 *
 */
public class DriveTrain extends Subsystem {

  private final SpeedController driveTrainFrontL = RobotMap.driveTrainFrontL;
  private final SpeedController driveTrainFrontR = RobotMap.driveTrainFrontR;
  private final SpeedController driveTrainBackL = RobotMap.driveTrainBackL;
  private final SpeedController driveTrainBackR = RobotMap.driveTrainBackR;

  public final void initDefaultCommand() {
    setDefaultCommand(new Drive());
  }

  public final void setSpeeds(double left, double right) {
    driveTrainBackL.set(left);
    driveTrainBackR.set(-right);
    driveTrainFrontL.set(left);
    driveTrainFrontR.set(-right);
  }
}

